name: Deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Pega o codigo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Testar
        run: npm run test
      - name: build
        run: npm run build
      - name: deploy
        run: echo "deployed.."