name: Deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Pega o codigo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  teste:
    runs-on: ubuntu-latest
    steps: 
      - name: Pega o codigo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: teste
        run: npm run teste

  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Pega o codigo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        run: echo "deployed.."